from random import randint as ran
resp = [
    "¡Hola! Soy Athenea y tengo excelentes noticias para ti. Después de analizar tus tesis, he concluido que eres oficialmente un maestro Jedi de tu campo de estudio. También hemos preparado un PDF con los resultados de tu análisis, así que prepárate para impresionar a todos tus colegas. ¡Que la fuerza te acompañe!",
    "¡Listo! Tu tesis ha sido analizada, como dijo el gran Mario Bros: 'It's-a me, Athenea!'.",
    "Tu tesis está lista, como diría Darth Vader: 'Impresionante, la fuerza es fuerte en esta. Athenea, has cumplido con tu deber.'",
    "Athenea ha terminado de analizar tu tesis. ¡Es como si hubiéramos ganado la batalla contra los Decepticons!",
    "¡Excelente! Athenea ha terminado de analizar tu tesis. Como diría el Doc Emmett Brown: '¡Es un éxito, Marty!'",
    "La tesis ha sido analizada, y Athenea dice: 'Toto, creo que ya no estamos en Kansas'.",
    "¡Lo logramos! Athenea ha terminado de analizar tu tesis. Como diría Will Smith en 'Men in Black': '¡Aquí viene el Hombre de Negro!'",
    "Athenea ha completado el análisis de tu tesis, como diría Rocky Balboa: '¡Adriaaaaan!'",
    "Tu tesis ha sido analizada, como diría el famoso detective Sherlock Holmes: '¡Elemental, mi querido Watson!'",
    "Athenea ha terminado de analizar tu tesis. ¡Es como si el poder de la fuerza estuviera de nuestro lado, como en Star Wars!",
    "¡Excelente trabajo! Tu tesis ha sido analizada y todo parece estar en orden. Athenea dice: '¡Yo soy Iron Man!'",
    "Athenea ha concluido el análisis de tu tesis, como diría el Capitán Kirk de Star Trek: '¡Haz que suceda, Número Uno!'",
    "¡Genial! Tu tesis ha sido analizada con éxito. Athenea dice: '¡Hasta la vista, baby!', como diría Terminator.",
    "Athenea ha terminado de analizar tu tesis. Como diría Marty McFly de 'Volver al Futuro': '¡Esto es pesado!'",
    "La tesis ha sido analizada y todo parece estar en orden. Athenea dice: '¡Que la fuerza te acompañe!', como en Star Wars.",
    "Athenea ha concluido el análisis de tu tesis, como diría el personaje de 'Tron': '¡Estoy en la red!'",
    "¡Lo logramos! Athenea ha terminado de analizar tu tesis. Como diría el gran MacGyver: 'Con un poco de cinta adhesiva y un lápiz, puedes hacer cualquier cosa'.",
    "Tu tesis ha sido analizada con éxito. Athenea dice: '¡Alohomora!', como diría Harry Potter.",
    "Athenea ha completado el análisis de tu tesis, como diría el famoso Spock de Star Trek: 'Vida larga y próspera'.",
    "¡Increíble! Tu tesis ha sido analizada con éxito. Como diría el personaje de 'Matrix': '¡Despierta, Neo!'",
    "¡Athenea ha terminado de analizar tu tesis! Ahora es hora de demostrar tus habilidades como el Rey de los Mares y sumergirte en el mundo de los datos.",
    "¡Felicitaciones! Athenea ha completado su análisis de tu tesis y ha encontrado más pistas que Batman en su Batcueva.",
    "¡Alto ahí, héroe! Athenea ha completado su análisis de tu tesis y ha descubierto más secretos que la armadura de Iron Man.",
    "¡Athenea ha terminado de analizar tu tesis! Ahora tienes la fuerza de Hulk para defender tus resultados.",
    "¡Genial! Athenea ha completado su análisis de tu tesis y ha descubierto más pistas que el Detective Marciano.",
    "¡Alabado sea Rao! Athenea ha terminado de analizar tu tesis y ha encontrado más secretos que la Fortaleza de la Soledad de Superman.",
    "¡Excelente trabajo! Athenea ha completado su análisis de tu tesis y ha descubierto más pistas que la Flecha Verde en su Quiver.",
    "¡Increíble! Athenea ha terminado de analizar tu tesis y ha encontrado más secretos que el Sanctum Sanctorum del Doctor Strange.",
    "¡Athenea ha completado su análisis de tu tesis! Ahora es hora de canalizar tus poderes de Spider-Man y lanzarte a la web de resultados.",
    "¡Fantástico! Athenea ha terminado de analizar tu tesis y ha encontrado más secretos que la Zona Negativa de los Cuatro Fantásticos.",
    "¡Athenea ha completado su análisis de tu tesis! Ahora es hora de usar tus habilidades de transformación como Mystique y adaptarte a los resultados.",
    "¡Impresionante! Athenea ha terminado de analizar tu tesis y ha descubierto más pistas que la Baticueva de Batman.",
    "¡Athenea ha completado su análisis de tu tesis! Ahora es hora de controlar tus habilidades como el Profesor X y navegar por los resultados.",
    "¡Magnífico! Athenea ha terminado de analizar tu tesis y ha encontrado más secretos que la Biblioteca del Sanctum Sanctorum.",
    "¡Athenea ha completado su análisis de tu tesis! Ahora es hora de poner en práctica tus habilidades de Iron Fist y puñetear los resultados.",
    "¡Sensacional! Athenea ha terminado de analizar tu tesis y ha descubierto más pistas que la Mansión X del Profesor X.",
    "¡Athenea ha completado su análisis de tu tesis! Ahora es hora de volar con tus habilidades de Phoenix y absorber los resultados.",
    "¡Espectacular! Athenea ha terminado de analizar tu tesis y ha encontrado más secretos que el Helitransporte de Nick Fury.",
    "¡Athenea ha completado su análisis de tu tesis! Ahora es hora de usar tus habilidades de Black Widow y espiar los resultados.",
    "¡Genial! Athenea ha terminado de analizar tu tesis y ha descubierto más pistas que el Planeta Krypton de Superman",
    "¡Bazinga! Hemos terminado de analizar tus tesis, y los resultados están listos en un PDF.",
    "El poder de Athenea ha sido liberado y el análisis de tu tesis está completo. Descarga el PDF para ver los resultados.",
    "¡Excelente! Athenea ha analizado tu tesis y los resultados están disponibles en un PDF.",
    "¡Cowabunga! El análisis de tu tesis ha sido completado por Athenea y el PDF con los resultados está listo para ser descargado.",
    "Athenea ha sacado su varita mágica y ha terminado de analizar tu tesis. Descarga el PDF para ver los resultados.",
    "Hemos analizado tu tesis y los resultados están listos para ser descargados en un PDF. ¡Que la fuerza te acompañe!"
]

def messageResp():
    return resp[ran(0, len(resp))]